### ISSUE TITLE
Could not load libMaxPayne.so

### ISSUE THREAD

**Issue by jzarca01** [fgsfdsfgs/max_nx#1]
Hi

I followed your instructions but I have this error when I try to start to game from hbmenu
Here is the maxpayne folder on my switch sdcard

https://imgur.com/a/MTNyAcJ

**Comment by fgsfdsfgs** [comment]
That `libMaxPayne.so` is extremely small. Should be around 13MB, yours is closer to 1MB. You sure it didn't get corrupted during transfer or something?

**Comment by jzarca01** [comment]
You were right about libMaxPayne.so although I keep having the same error.

How can I provide a useful log ?

**Comment by fgsfdsfgs** [comment]
What's the size of it now?

**Comment by jzarca01** [comment]
14,3MB

**Comment by fgsfdsfgs** [comment]
The exact size should be `14 314 072` bytes. That error can only indicate one of three things:
* it can't find the .so file;
* the .so file is corrupted;
* you got the wrong version of the .so file.
If you were copying files from OSX or something, try unsetting the archive flag on all the files inside the folder.
Also make sure you're not running hbmenu from the album, that shit doesn't provide enough memory.

**Comment by jzarca01** [comment]
I downloaded the apk from here https://apkvision.com/download/?item=52962&to=files_url so it should be the right version
Let's assume it's not corrupted, the correct path for the file is /switch/maxpayne/libMaxPayne.so right ?

**Comment by fgsfdsfgs** [comment]
Please don't post links to copyrighted material. The path is correct. I don't know what to tell you then. exfat memes?

**Comment by fgsfdsfgs** [comment]
Here, try this. It should produce a log file called `debug.log` in the game folder.
[max_nx.zip](https://github.com/fgsfdsfgs/max_nx/files/6050115/max_nx.zip)

**Comment by jzarca01** [comment]
I tried starting all over again but still no luck
Here's what's inside the debug file

screen mode: 1280x720
heap size = 524288 KB
 lib base = 0xa07800000
  lib max = 0 KB

**Comment by fgsfdsfgs** [comment]
Are you running the game from the album?

**Comment by jzarca01** [comment]
It's not even showing in the album, the only way to run the game I have for now is through hbmenu

Wouldn't it solve things to place the nro file in /switch and let it browse files from /switch/maxpayne ?

**Comment by fgsfdsfgs** [comment]
The log is literally reporting that you have 0KB free memory after the newlib heap is allocated. I've only had this happen when running the game through the album override. What are you using to run hbmenu?

**Comment by jzarca01** [comment]
SXOS ?

**Comment by fgsfdsfgs** [comment]
I have no idea how exactly it's set up in SX OS, but it would seem that it runs in applet mode. Does it provide game override functionality? Like "hold R while launching a game to enter hbmenu"? You should use that if it does. If it doesn't, maybe try [this](https://gbatemp.net/threads/homebrew-menu-loader-legal-nsp.518433/).

**Comment by jzarca01** [comment]
Ok so I install hbmenu from your link, ran it while holding R and I get the same error except that this time debug.log shows this

screen mode: 1280x720
heap size = 524288 KB
 lib base = 0x1ff1a9000
  lib max = 2826588 KB

**Comment by fgsfdsfgs** [comment]
Here, this should give a bit more debug info. Nuke the old log and try running this NRO.
[max_nx2.zip](https://github.com/fgsfdsfgs/max_nx/files/6050990/max_nx2.zip)

**Comment by jzarca01** [comment]
ok I finally got it working !!!

thanks a lot for your help, you made my weekend :)

**Comment by fgsfdsfgs** [comment]
Well, that's weird. What was the problem?

**Comment by jzarca01** [comment]
libMaxPayne.so got deleted at some point for no reason
