### ISSUE TITLE
Final Fantasy 4: The After Years Nintendo switch wrapper/port

### ISSUE THREAD

**Issue by Tokobotenkai** [fgsfdsfgs/max_nx#6]
Hi,

I couldn't find a way to contact you but I was wondering if I could adapt your existing files to do it for the Android version of FF4: The After Years.

I don't know much programming but I guess that the wrapper works for different android games with perhaps patches/links that are game specific.

Any idea how could I get started?

But then again, there's a PC version on Steam but I am unsure if going for some kind of Switchroot L4T Ubuntu with Box86+proton would be better,

**Comment by fgsfdsfgs** [comment]
If you're willing to use Switchroot, you can just install Android on the thing and just play any Android game.
Quite a bit has to be done manually to adapt the wrapper to other games, on top of that I don't know if Android FF4 has aarch64 binaries. If it does not, then installing Android is your only option.

**Comment by Tokobotenkai** [comment]
Ah, I understand. I thought it was something like a general wrapper that runs something in like a QEMU/Wine layer.

I will try the android binaries then. Thanks!
